language: python
python:
   - 2.6
   - 2.7
before_install:
   - sudo apt-get install fabric python-requests
install:
   - if [ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]; then
       pip install -r dev_requirements26.txt;
       else
       pip install -r dev_requirements.txt;
       fi
   - pip install coveralls
   - python setup.py develop
script:
   - coverage run --source=enstaller,egginst -a -m nose.core enstaller egginst
   - coverage run --source=enstaller,egginst -a -m nose.core tests/functional
after_success:
    coveralls
notifications:
  email:
    - davidc@enthought.com
    - cwebster@enthought.com
