language: python

matrix:
   - 2.6
     RUN_INPLACE_UPGRADE=0
   - 2.7
     RUN_INPLACE_UPGRADE=0
   - 2.7
     RUN_INPLACE_UPGRADE=1
   - 3.3
     RUN_INPLACE_UPGRADE=0
   - 3.4
     RUN_INPLACE_UPGRADE=0

before_install:
   - if [ "${RUN_INPLACE_UPGRADE}" -eq 1 ]; then
     sudo apt-get install fabric python-requests
     fi

install:
   - if [ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]; then
       pip install -r dev_requirements26.txt;
       else
       pip install -r dev_requirements.txt;
       fi
   - pip install coveralls
   - python setup.py develop

script:
   - if [ "${RUN_INPLACE_UPGRADE}" -eq 1 ]; then
       fab -f tests/inplace_upgrade/test_update.py run_enstaller_upgrade;
       else
       coverage run --source=enstaller,egginst -a -m haas enstaller egginst;
       coverage run --source=enstaller,egginst -a -m haas tests/functional;
       fi


after_success:
    coveralls

notifications:
  email:
    - davidc@enthought.com
    - cwebster@enthought.com
