language: python
python:
   - 2.6
   - 2.7
install:
   - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=enstaller --cover-inclusive enstaller
notifications:
  email:
    - davidc@enthought.com
