language: python
python:
   - 2.6
   - 2.7
install:
   - if [ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]; then
       pip install -r dev_requirements26.txt;
       else
       pip install -r dev_requirements.txt;
       fi
   - python setup.py develop
script:
  - nosetests --randomize --with-coverage --cover-package=egginst,enstaller enstaller egginst
notifications:
  email:
    - davidc@enthought.com
    - cwebster@enthought.com
