language: python

matrix:
    include:
        #- python: 2.6
        #  env: TEST_INPLACE_UPGRADE=0
        #- python: 2.7
        #  env: TEST_INPLACE_UPGRADE=0
        - python: 2.7
          env: TEST_INPLACE_UPGRADE=1
        #- python: 3.3
        #  env: TEST_INPLACE_UPGRADE=0
        #- python: 3.4
        #  env: TEST_INPLACE_UPGRADE=0

before_install:
   - if [ "${TEST_INPLACE_UPGRADE}" == "1" ]; then
       sudo apt-get install fabric python-requests python-pip;
       pip install pathlib;
       fi

install:
   - if [ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]; then
       pip install -r dev_requirements26.txt;
       else
       pip install -r dev_requirements.txt;
       fi
   - pip install coveralls
   - python setup.py develop

script:
   - if [ "${TEST_INPLACE_UPGRADE}" == "1" ]; then
       fab -f tests/inplace_upgrade/test_update.py run_enstaller_upgrade;
       else
       coverage run --source=enstaller,egginst -a -m haas enstaller egginst;
       coverage run --source=enstaller,egginst -a -m haas tests/functional;
       fi

after_success:
    coveralls

notifications:
  email:
    - davidc@enthought.com
    - cwebster@enthought.com
